import React, { useState } from "react";
import { ActionTask } from "../../services/performanceEngine";

interface DailyScheduleCardProps {
  tasks: ActionTask[];
  planGeneratedTime: string;
  onToggleTask: (taskId: string) => void;
}

// Professional AI Task Timeline Component (Redesigned Today's Personalized Action Plan)
export const DailyScheduleCard: React.FC<DailyScheduleCardProps> = ({
  tasks,
  planGeneratedTime,
  onToggleTask,
}) => {
  const [expandedHistory, setExpandedHistory] = useState<Record<string, boolean>>({});

  const toggleHistory = (taskId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setExpandedHistory((prev) => ({ ...prev, [taskId]: !prev[taskId] }));
  };

  const completedCount = tasks.filter((t) => t.status === "Completed").length;
  const rolledOverCount = tasks.filter((t) => t.status === "Rolled Over").length;
  const pendingCount = tasks.filter((t) => t.status !== "Completed").length;
  const totalCount = tasks.length;
  const completionRate = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
  const estimatedTimeMins = pendingCount * 40;
  const estimatedHours = Math.floor(estimatedTimeMins / 60);
  const estimatedMins = estimatedTimeMins % 60;
  const estimatedTimeStr = `${estimatedHours} hrs ${estimatedMins} mins`;

  const isAllCompleted = totalCount > 0 && completedCount === totalCount;

  // Badge styles helper
  const getPriorityBadgeStyle = (p: string) => {
    switch (p) {
      case "High":
        return "bg-red-500/20 text-red-300 border-red-500/40 shadow-sm shadow-red-500/10";
      case "Medium":
        return "bg-amber-500/20 text-amber-300 border-amber-500/30";
      case "Low":
      default:
        return "bg-emerald-500/20 text-emerald-300 border-emerald-500/30";
    }
  };

  const getStatusBadgeStyle = (s: string) => {
    switch (s) {
      case "Completed":
        return "bg-emerald-500/20 text-emerald-300 border-emerald-500/40";
      case "Rolled Over":
        return "bg-rose-500/20 text-rose-300 border-rose-500/40";
      case "Pending":
        return "bg-amber-500/20 text-amber-300 border-amber-500/30";
      case "New":
      default:
        return "bg-cyan-500/20 text-cyan-300 border-cyan-500/30";
    }
  };

  const getSourceBadgeText = (createdBy: string) => {
    switch (createdBy) {
      case "AI":
        return "Generated by AI";
      case "User":
        return "Generated by User";
      case "Recurring":
        return "Recurring Task";
      default:
        return "Generated by AI";
    }
  };

  return (
    <div className="glass-card p-6 md:p-8 rounded-3xl border border-white/10 space-y-8 bg-gradient-to-br from-[#1a1a2e]/80 via-[#16162a]/70 to-[#0f0f1b]/90 backdrop-blur-xl shadow-2xl">
      {/* 1. SECTION HEADER */}
      <div className="space-y-4 border-b border-white/10 pb-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h2 className="font-headline font-bold text-2xl text-white tracking-tight flex items-center gap-2.5">
              <span className="material-symbols-outlined text-[#c3c0ff] text-2xl">timeline</span>
              <span>Today's Personalized Action Plan</span>
            </h2>
            <p className="text-xs text-[#c7c4d8] mt-1">
              AI-generated daily work plan tracking full task lifecycles, rollovers, and performance impacts
            </p>
          </div>

          <div className="flex items-center gap-2 self-start md:self-auto">
            <span className="px-3.5 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-bold flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
              <span>Plan Status: Active</span>
            </span>
          </div>
        </div>

        {/* Metadata Header Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
          <div className="p-3 rounded-2xl bg-white/5 border border-white/10 space-y-0.5">
            <span className="text-[10px] font-bold text-[#c3c0ff] uppercase tracking-wider block">Plan Generated</span>
            <p className="text-xs font-bold text-white font-mono">{planGeneratedTime}</p>
          </div>

          <div className="p-3 rounded-2xl bg-white/5 border border-white/10 space-y-0.5">
            <span className="text-[10px] font-bold text-[#c3c0ff] uppercase tracking-wider block">Daily Progress</span>
            <p className="text-xs font-bold text-white">{completedCount} / {totalCount} Tasks Completed</p>
          </div>

          <div className="p-3 rounded-2xl bg-white/5 border border-white/10 space-y-0.5">
            <span className="text-[10px] font-bold text-[#c3c0ff] uppercase tracking-wider block">Est. Completion Time</span>
            <p className="text-xs font-bold text-white">{estimatedTimeStr}</p>
          </div>

          <div className="p-3 rounded-2xl bg-white/5 border border-white/10 space-y-0.5">
            <span className="text-[10px] font-bold text-[#c3c0ff] uppercase tracking-wider block">Completion Rate</span>
            <p className="text-xs font-bold text-emerald-400">{completionRate}%</p>
          </div>
        </div>
      </div>

      {/* 2. ALL COMPLETED CONGRATULATIONS EMPTY STATE */}
      {isAllCompleted && (
        <div className="p-8 rounded-3xl bg-gradient-to-r from-emerald-500/20 via-teal-500/10 to-emerald-500/20 border border-emerald-500/30 text-center space-y-3 shadow-xl animate-fade-in">
          <div className="text-4xl">🎉</div>
          <h3 className="font-headline font-black text-2xl text-white">Congratulations!</h3>
          <p className="text-sm text-emerald-200 font-medium max-w-lg mx-auto">
            You completed all of today's AI-generated tasks. Your action plan contributed +{completedCount * 2} points to your overall performance score!
          </p>
          <p className="text-xs text-[#c7c4d8]">
            Tomorrow's action plan will be generated automatically at 8:00 AM based on your activity today.
          </p>
        </div>
      )}

      {/* 3. TASK CARDS LIST */}
      <div className="space-y-5">
        {tasks.map((task) => {
          const isCompleted = task.status === "Completed";
          const isRolledOver = task.status === "Rolled Over";
          const showHistory = expandedHistory[task.id];

          return (
            <div
              key={task.id}
              onClick={() => onToggleTask(task.id)}
              className={`p-5 md:p-6 rounded-3xl border transition-all duration-300 cursor-pointer space-y-4 group relative overflow-hidden ${
                isCompleted
                  ? "bg-emerald-500/5 border-emerald-500/30 shadow-lg shadow-emerald-500/5 opacity-95"
                  : isRolledOver
                  ? "bg-rose-500/5 border-rose-500/30 shadow-lg shadow-rose-500/5 hover:border-rose-500/50"
                  : "bg-white/[0.03] border-white/10 hover:border-white/20 shadow-xl"
              }`}
            >
              {/* Top Row: Checkbox, Title & Badges */}
              <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                <div className="flex items-start gap-4">
                  {/* Interactive Checkbox */}
                  <div
                    className={`w-7 h-7 rounded-xl flex items-center justify-center transition-all duration-300 shrink-0 mt-0.5 ${
                      isCompleted
                        ? "bg-emerald-500 text-black shadow-lg shadow-emerald-500/40 font-black text-base scale-105"
                        : "border-2 border-white/30 group-hover:border-[#c3c0ff] text-transparent hover:scale-105"
                    }`}
                  >
                    ✓
                  </div>

                  <div className="space-y-1.5">
                    <div className="flex flex-wrap items-center gap-2">
                      <h3
                        className={`font-headline font-bold text-lg leading-tight transition-colors ${
                          isCompleted ? "line-through text-emerald-300/80" : "text-white group-hover:text-[#c3c0ff]"
                        }`}
                      >
                        {task.title}
                      </h3>

                      {/* Source Tag */}
                      <span className="text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full bg-white/5 border border-white/10 text-[#c3c0ff]">
                        {getSourceBadgeText(task.createdBy)}
                      </span>

                      {/* Pending Counter Badge for Rolled Over Tasks */}
                      {isRolledOver && !isCompleted && (
                        <span className="text-[10px] font-black uppercase tracking-wider px-2.5 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/40 animate-pulse">
                          Pending for {task.pendingDays || 1} Day{task.pendingDays && task.pendingDays > 1 ? "s" : ""}
                        </span>
                      )}
                    </div>

                    {task.description && (
                      <p className="text-xs text-[#c7c4d8] leading-relaxed">{task.description}</p>
                    )}
                  </div>
                </div>

                {/* Badges: Priority & Status */}
                <div className="flex items-center gap-2 shrink-0 self-start sm:self-auto pl-11 sm:pl-0">
                  <span className={`text-[10px] font-bold uppercase tracking-wider px-3 py-1 rounded-full border ${getPriorityBadgeStyle(task.priority)}`}>
                    Priority: {task.priority}
                  </span>
                  <span className={`text-[10px] font-bold uppercase tracking-wider px-3 py-1 rounded-full border ${getStatusBadgeStyle(task.status)}`}>
                    {task.status}
                  </span>
                </div>
              </div>

              {/* Lifecycle Dates Bar */}
              <div className="flex flex-wrap items-center gap-4 text-[11px] text-[#c7c4d8] pt-2 border-t border-white/5 pl-11">
                <span>Assigned: <strong className="text-white font-medium">{task.assignedDate}</strong></span>

                {isCompleted && task.completedDate && (
                  <span>Completed: <strong className="text-emerald-400 font-semibold">{task.completedDate}</strong></span>
                )}

                {isRolledOver && !isCompleted && task.rolledOverDate && (
                  <span>Rolled Over: <strong className="text-rose-300 font-semibold">{task.rolledOverDate}</strong></span>
                )}

                <span>Due: <strong className="text-white font-medium">{task.dueDate}</strong></span>
              </div>

              {/* AI Reason or AI Comment */}
              <div className="ml-11 p-3.5 rounded-2xl bg-white/5 border border-white/5 space-y-1">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-xs text-[#c3c0ff]">auto_awesome</span>
                  <span className="text-[10px] font-bold text-[#c3c0ff] uppercase tracking-wider">
                    {isCompleted ? "AI Performance Impact" : "AI Reason"}
                  </span>
                </div>

                <p className="text-xs text-white/90 leading-relaxed font-normal">
                  {isCompleted && task.aiComment ? task.aiComment : task.reason}
                </p>

                {isCompleted && task.impactOnPerformance && (
                  <div className="pt-1 flex items-center gap-2">
                    <span className="px-2.5 py-0.5 rounded-md bg-emerald-500/20 text-emerald-300 text-[10px] font-extrabold border border-emerald-500/30">
                      Impact: {task.impactOnPerformance}
                    </span>
                  </div>
                )}
              </div>

              {/* Collapsible Task History Lifecycle */}
              {task.history && task.history.length > 0 && (
                <div className="ml-11 pt-1">
                  <button
                    onClick={(e) => toggleHistory(task.id, e)}
                    className="text-[11px] font-semibold text-[#c3c0ff] hover:text-white flex items-center gap-1 transition-colors"
                  >
                    <span className="material-symbols-outlined text-xs">history</span>
                    <span>Task History ({task.history.length})</span>
                    <span className="material-symbols-outlined text-xs">
                      {showHistory ? "expand_less" : "expand_more"}
                    </span>
                  </button>

                  {showHistory && (
                    <div className="mt-2.5 p-3 rounded-2xl bg-black/30 border border-white/10 space-y-2 text-xs">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-[#c7c4d8] block">Task Lifecycle Audit</span>
                      <div className="space-y-1.5">
                        {task.history.map((h, hIdx) => (
                          <div key={hIdx} className="flex items-center justify-between text-[11px]">
                            <span className="text-[#c3c0ff] font-mono">{h.date}</span>
                            <span className="text-white font-medium">{h.action}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* 4. BOTTOM PROGRESS SUMMARY */}
      <div className="p-6 rounded-3xl bg-white/5 border border-white/10 space-y-4">
        <h3 className="font-headline font-bold text-base text-white flex items-center gap-2">
          <span className="material-symbols-outlined text-[#c3c0ff]">analytics</span>
          <span>Today's Progress Summary</span>
        </h3>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-center space-y-1">
            <span className="text-[10px] font-bold uppercase tracking-widest text-emerald-400">Completed</span>
            <p className="text-2xl font-headline font-black text-white">{completedCount}</p>
          </div>

          <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-center space-y-1">
            <span className="text-[10px] font-bold uppercase tracking-widest text-amber-400">Pending</span>
            <p className="text-2xl font-headline font-black text-white">{pendingCount}</p>
          </div>

          <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/20 text-center space-y-1">
            <span className="text-[10px] font-bold uppercase tracking-widest text-rose-400">Rolled Over</span>
            <p className="text-2xl font-headline font-black text-white">{rolledOverCount}</p>
          </div>

          <div className="p-4 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 text-center space-y-1">
            <span className="text-[10px] font-bold uppercase tracking-widest text-cyan-400">Completion Rate</span>
            <p className="text-2xl font-headline font-black text-white">{completionRate}%</p>
          </div>
        </div>
      </div>
    </div>
  );
};
